# Generated by Django 4.2.5 on 2023-12-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', models.TextField(max_length=200)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(max_length=500)),
                ('points', models.CharField(max_length=20, null=True)),
                ('comment', models.CharField(max_length=80, null=True)),
                ('submission_date', models.DateField()),
                ('assign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.assignment')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.batch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.teacher'),
        ),
    ]
